### ISSUE TITLE
post_ok doesn't recognize any LWP_options

### ISSUE THREAD

**Issue by petdance** [petdance/test-www-mechanize#18]
The hashref of `LWP_options` for `post_ok` is passed to `$mech->post` as a reference instead of as a list. This means that it is useless for setting any request options (Content-Type is the one I care about here), and can only set form parameters.

Compare (from post_ok):

```
$self->post( $url, \%opts );
```

vs. (from get_ok)

```
$self->get( $url, %opts );
```

Fix `post_ok` method and pass `%opts` to the <post> method instead of `\%opts`.

**Comment by adsj** [comment]
I just hit this problem as well, trying to simulate an LWP::UserAgent->post($url, Content=>'...', 'Content_Type'=>'application/json') call.

Traced the problem to post_ok() passing options as a hash-ref to LWP::UserAgent->post (via WWW::Mechanize) instead of a hash.

**Comment by dimentox** [comment]
This has bit a ton of people.  You have a PR, and you have an issue but yet you don't want to fix.. 
Its not like this is a huge lib id say fork it but they have "claimed" the namespace" ohhh lovely perl cpan woes.

**Comment by zakame** [comment]
Ran into this as well, bumping.

:shipit:

**Comment by TJC** [comment]
+1 -- just wasted a while trying to figure out why the content-type wasn't getting set correctly in my unit tests :(
