### ISSUE TITLE
Add xml_lint_ok()

### ISSUE THREAD

**Issue by heytitle** [petdance/test-www-mechanize#35]
It would be great if Test::WWW::Mechanize has xml_lint_ok(). Testing xml will be much easier.

```
$mech->xml_lint_ok( '/sitemap.xml' );
```

What do you think?

**Comment by petdance** [comment]
What are you doing to deal with this now?  Manually running a lint?  What lint tool are you using?

**Comment by petdance** [comment]
Closed for lack of interest.
