### ISSUE TITLE
Dependency on HTML::TreeBuilder not clear 

### ISSUE THREAD

**Issue by kentfredric** [petdance/test-www-mechanize#58]
https://github.com/petdance/test-www-mechanize/blob/dev/Makefile.PL#L16 

This was added back in 1.30, but its not clear exactly why.

The best I have is that this is a dependency of WWW::Mechanize , but even then, my analysis of that indicates its a very weak dependency.

Digging into WWW::Mechanize, this is here as a supporting feature for `$mech->content( format => 'text' )`

But I don't see that feature used anywhere by T:W:M.

So this request is to either:
1. Remove the dependency
2. Weaken the dependency ( eg: make it test-only, or recommended, or suggested, etc )
3. Document the reason for the dependency clearly somewhere

Additionally, @libwww-perl may find scope to perform similar dependency weakening in WWW-Mechanize

**Comment by petdance** [comment]
Done.  Thank you.  64c8e18
